from sqlalchemy import Column, String, Float, Text, Boolean, ForeignKey, DateTime
from .base import Base, TimestampMixin, generate_uuid


class AlertType:
    SEVERITY_SPIKE = "severity_spike"
    STALLED_WOUND = "stalled_wound"
    STAGE_4_PREDICTED = "stage_4_predicted"
    GENERAL = "general"


class AlertSeverity:
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Alert(Base, TimestampMixin):
    """Clinical alert generated by the rule-based alert engine."""
    __tablename__ = "alerts"

    id = Column(String, primary_key=True, default=generate_uuid)
    wound_id = Column(String, ForeignKey("wounds.id"), nullable=False, index=True)
    patient_id = Column(String, ForeignKey("patients.id"), nullable=False, index=True)
    alert_type = Column(String(50), nullable=False)
    severity = Column(String(20), nullable=False, default=AlertSeverity.MEDIUM)
    message = Column(Text, nullable=False)
    is_read = Column(Boolean, default=False, nullable=False)


class AlertRule(Base, TimestampMixin):
    """Configurable rule definition for the alert engine."""
    __tablename__ = "alert_rules"

    id = Column(String, primary_key=True, default=generate_uuid)
    name = Column(String(100), nullable=False)
    condition_type = Column(String(50), nullable=False)
    threshold = Column(Float, nullable=True)
    is_active = Column(Boolean, default=True, nullable=False)
