"""
PDF wound assessment report generator.
Uses reportlab to produce printable reports suitable for clinical records and EHR attachment.
"""
from io import BytesIO
from datetime import datetime, timezone
from typing import Optional, Dict, List

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


class WoundReportGenerator:
    """Generate PDF wound assessment reports."""

    def generate(
        self,
        patient_name: str,
        patient_mrn: str,
        wound_id: str,
        wound_etiology: str,
        wound_location: str,
        scans: List[Dict],
        generated_by: str,
    ) -> bytes:
        """Return PDF bytes for a wound assessment report.

        ``scans`` is a list of dicts with keys matching the Scan model fields
        (area_cm2, severity_score, stage_classification, treatment_recommendation,
        tissue_granulation_pct, tissue_slough_pct, tissue_eschar_pct, par_from_baseline,
        created_at, scanned_by).
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=0.75 * inch,
            rightMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
        )
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Title"],
            fontSize=18,
            spaceAfter=12,
        )
        heading_style = ParagraphStyle(
            "SectionHeading",
            parent=styles["Heading2"],
            fontSize=13,
            spaceBefore=14,
            spaceAfter=6,
            textColor=colors.HexColor("#2c3e50"),
        )
        body = styles["BodyText"]

        elements: list = []

        # --- Header ---
        elements.append(Paragraph("NoPressure — Wound Assessment Report", title_style))
        elements.append(Spacer(1, 6))
        meta_data = [
            ["Patient Name:", patient_name, "MRN:", patient_mrn],
            ["Wound ID:", wound_id, "Etiology:", wound_etiology],
            ["Location:", wound_location, "Report Date:", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")],
            ["Generated By:", generated_by, "", ""],
        ]
        meta_table = Table(meta_data, colWidths=[1.3 * inch, 2.2 * inch, 1.3 * inch, 2.2 * inch])
        meta_table.setStyle(TableStyle([
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(meta_table)
        elements.append(Spacer(1, 14))

        # --- Scan history table ---
        if scans:
            elements.append(Paragraph("Scan History", heading_style))
            header = ["Date", "Scanned By", "Area (cm²)", "PAR %", "Severity", "Stage"]
            rows = [header]
            for s in scans:
                created = s.get("created_at", "")
                if isinstance(created, datetime):
                    created = created.strftime("%Y-%m-%d")
                rows.append([
                    str(created),
                    str(s.get("scanned_by", "")),
                    str(round(s["area_cm2"], 2)) if s.get("area_cm2") is not None else "—",
                    str(round(s["par_from_baseline"], 1)) if s.get("par_from_baseline") is not None else "—",
                    str(round(s["severity_score"], 1)) if s.get("severity_score") is not None else "—",
                    str(s.get("stage_classification", "—")),
                ])
            scan_table = Table(rows, repeatRows=1)
            scan_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#34495e")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
            ]))
            elements.append(scan_table)
            elements.append(Spacer(1, 10))

        # --- Latest scan details ---
        if scans:
            latest = scans[-1]
            elements.append(Paragraph("Latest Assessment Details", heading_style))

            tissue_text = (
                f"Granulation: {latest.get('tissue_granulation_pct', 0):.1f}%, "
                f"Slough: {latest.get('tissue_slough_pct', 0):.1f}%, "
                f"Eschar: {latest.get('tissue_eschar_pct', 0):.1f}%"
            )
            elements.append(Paragraph(f"<b>Tissue Composition:</b> {tissue_text}", body))
            elements.append(Spacer(1, 4))

            rec = latest.get("treatment_recommendation") or {}
            if isinstance(rec, dict) and rec.get("primary_dressing"):
                elements.append(Paragraph(
                    f"<b>Recommended Dressing:</b> {rec['primary_dressing']}", body
                ))
                interventions = rec.get("interventions", [])
                if interventions:
                    elements.append(Paragraph(
                        f"<b>Interventions:</b> {'; '.join(interventions)}", body
                    ))
                elements.append(Spacer(1, 4))

            notes = latest.get("clinical_notes")
            if notes:
                elements.append(Paragraph(f"<b>Clinical Notes:</b> {notes}", body))
                elements.append(Spacer(1, 4))

        # --- Footer / disclaimer ---
        elements.append(Spacer(1, 20))
        disclaimer = ParagraphStyle("Disclaimer", parent=body, fontSize=7, textColor=colors.grey)
        elements.append(Paragraph(
            "This report is generated by the NoPressure clinical platform. "
            "AI-derived measurements and classifications should be confirmed by a licensed clinician.",
            disclaimer,
        ))

        doc.build(elements)
        return buffer.getvalue()


report_generator = WoundReportGenerator()
